# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateStrategy',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('financialYear', models.CharField(max_length=100, choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')])),
                ('corporateStrategyNo', models.CharField(max_length=100)),
                ('description1', models.TextField(null=True)),
                ('description2', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'corporate strategies',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ERServicePriority',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('financialYear', models.CharField(max_length=100, choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')])),
                ('categoryID', models.CharField(max_length=100, null=True, blank=True)),
                ('servicePriorityNo', models.CharField(default='-1', max_length=100)),
                ('strategicPlanNo', models.CharField(max_length=100, null=True, blank=True)),
                ('corporateStrategyNo', models.CharField(max_length=100, null=True, blank=True)),
                ('description', models.TextField(null=True)),
                ('pvsExampleAnnWP', models.TextField()),
                ('pvsExampleActNo', models.TextField()),
                ('classification', models.TextField()),
            ],
            options={
                'verbose_name': 'ER service priority',
                'verbose_name_plural': 'ER service priorities',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GeneralServicePriority',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('financialYear', models.CharField(max_length=100, choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')])),
                ('categoryID', models.CharField(max_length=100, null=True, blank=True)),
                ('servicePriorityNo', models.CharField(default='-1', max_length=100)),
                ('strategicPlanNo', models.CharField(max_length=100, null=True, blank=True)),
                ('corporateStrategyNo', models.CharField(max_length=100, null=True, blank=True)),
                ('description', models.TextField(null=True)),
                ('pvsExampleAnnWP', models.TextField()),
                ('pvsExampleActNo', models.TextField()),
                ('description2', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'general service priorities',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GLPivDownload',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('financialYear', models.CharField(max_length=7)),
                ('downloadPeriod', models.CharField(max_length=10)),
                ('costCentre', models.CharField(max_length=4)),
                ('account', models.IntegerField()),
                ('service', models.IntegerField()),
                ('activity', models.CharField(max_length=4)),
                ('resource', models.IntegerField()),
                ('project', models.CharField(max_length=6)),
                ('job', models.CharField(max_length=6)),
                ('shortCode', models.CharField(max_length=20)),
                ('shortCodeName', models.CharField(max_length=200)),
                ('gLCode', models.CharField(max_length=30)),
                ('ptdActual', models.DecimalField(max_digits=10, decimal_places=2)),
                ('ptdBudget', models.DecimalField(max_digits=10, decimal_places=2)),
                ('ytdActual', models.DecimalField(max_digits=10, decimal_places=2)),
                ('ytdBudget', models.DecimalField(max_digits=10, decimal_places=2)),
                ('fybudget', models.DecimalField(max_digits=12, decimal_places=2)),
                ('ytdVariance', models.DecimalField(max_digits=10, decimal_places=2)),
                ('ccName', models.CharField(max_length=100)),
                ('serviceName', models.CharField(max_length=100)),
                ('activityName', models.CharField(max_length=100)),
                ('resourceName', models.CharField(max_length=100)),
                ('projectName', models.CharField(max_length=100)),
                ('jobName', models.CharField(max_length=100)),
                ('codeID', models.CharField(help_text="This should match an IBMData object's IBMIdentifier field.", max_length=30)),
                ('resNameNo', models.CharField(max_length=100)),
                ('actNameNo', models.CharField(max_length=100)),
                ('projNameNo', models.CharField(max_length=100)),
                ('regionBranch', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('resourceCategory', models.CharField(max_length=100)),
                ('wildfire', models.CharField(max_length=30)),
                ('expenseRevenue', models.CharField(max_length=7)),
                ('fireActivities', models.CharField(max_length=50)),
                ('mPRACategory', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'GL pivot download',
                'verbose_name_plural': 'GL pivot downloads',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='IBMData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('financialYear', models.CharField(max_length=100, choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')])),
                ('ibmIdentifier', models.CharField(help_text='IBM Identifier', max_length=100, verbose_name='IBMId')),
                ('budgetArea', models.CharField(max_length=100)),
                ('projectSponsor', models.CharField(max_length=100)),
                ('corporatePlanNo', models.CharField(max_length=100)),
                ('strategicPlanNo', models.CharField(max_length=100)),
                ('regionalSpecificInfo', models.TextField()),
                ('servicePriorityID', models.CharField(max_length=100)),
                ('annualWPInfo', models.TextField()),
                ('costCentre', models.CharField(max_length=4, null=True, blank=True)),
                ('account', models.IntegerField(null=True, blank=True)),
                ('service', models.IntegerField(null=True, blank=True)),
                ('activity', models.CharField(max_length=4, null=True, blank=True)),
                ('project', models.CharField(max_length=6, null=True, blank=True)),
                ('job', models.CharField(max_length=6, null=True, blank=True)),
            ],
            options={
                'verbose_name': 'IBM data',
                'verbose_name_plural': 'IBM data',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='NCServicePriority',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('financialYear', models.CharField(max_length=100, choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')])),
                ('categoryID', models.CharField(max_length=100, null=True, blank=True)),
                ('servicePriorityNo', models.CharField(default='-1', max_length=100)),
                ('strategicPlanNo', models.CharField(max_length=100, null=True, blank=True)),
                ('corporateStrategyNo', models.CharField(max_length=100, null=True, blank=True)),
                ('description', models.TextField(null=True)),
                ('pvsExampleAnnWP', models.TextField()),
                ('pvsExampleActNo', models.TextField()),
                ('assetNo', models.CharField(max_length=5)),
                ('asset', models.TextField()),
                ('targetNo', models.CharField(max_length=30)),
                ('target', models.TextField()),
                ('actionNo', models.CharField(max_length=30)),
                ('action', models.TextField()),
                ('mileNo', models.CharField(max_length=30)),
                ('milestone', models.TextField()),
            ],
            options={
                'verbose_name': 'NC service priority',
                'verbose_name_plural': 'NC service priorities',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='NCStrategicPlan',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('financialYear', models.CharField(max_length=100, choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')])),
                ('strategicPlanNo', models.CharField(max_length=100)),
                ('directionNo', models.CharField(max_length=100)),
                ('direction', models.TextField()),
                ('AimNo', models.CharField(max_length=100)),
                ('Aim1', models.TextField()),
                ('Aim2', models.TextField()),
                ('ActionNo', models.TextField()),
                ('Action', models.TextField()),
            ],
            options={
                'verbose_name': 'NC strategic plan',
                'verbose_name_plural': 'NC strategic plans',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Outcomes',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('financialYear', models.CharField(max_length=7)),
                ('q1Input', models.TextField()),
                ('q2Input', models.TextField(blank=True)),
                ('q3Input', models.TextField(blank=True)),
                ('q4Input', models.TextField(blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PVSServicePriority',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('financialYear', models.CharField(max_length=100, choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')])),
                ('categoryID', models.CharField(max_length=100, null=True, blank=True)),
                ('servicePriorityNo', models.CharField(default='-1', max_length=100)),
                ('strategicPlanNo', models.CharField(max_length=100, null=True, blank=True)),
                ('corporateStrategyNo', models.CharField(max_length=100, null=True, blank=True)),
                ('description', models.TextField(null=True)),
                ('pvsExampleAnnWP', models.TextField()),
                ('pvsExampleActNo', models.TextField()),
                ('servicePriority1', models.TextField()),
            ],
            options={
                'verbose_name': 'PVS service priority',
                'verbose_name_plural': 'PVS service priorities',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SFMServicePriority',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('financialYear', models.CharField(max_length=100, choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')])),
                ('categoryID', models.CharField(max_length=100, null=True, blank=True)),
                ('servicePriorityNo', models.CharField(default='-1', max_length=100)),
                ('strategicPlanNo', models.CharField(max_length=100, null=True, blank=True)),
                ('corporateStrategyNo', models.CharField(max_length=100, null=True, blank=True)),
                ('description', models.TextField(null=True)),
                ('pvsExampleAnnWP', models.TextField()),
                ('pvsExampleActNo', models.TextField()),
                ('regionBranch', models.CharField(max_length=20)),
                ('description2', models.TextField()),
            ],
            options={
                'verbose_name': 'SFM service priority',
                'verbose_name_plural': 'SFM service priorities',
            },
            bases=(models.Model,),
        ),
        migrations.AlterUniqueTogether(
            name='ncstrategicplan',
            unique_together=set([('strategicPlanNo', 'financialYear')]),
        ),
        migrations.AlterUniqueTogether(
            name='ncservicepriority',
            unique_together=set([('servicePriorityNo', 'financialYear')]),
        ),
        migrations.AlterUniqueTogether(
            name='ibmdata',
            unique_together=set([('ibmIdentifier', 'financialYear')]),
        ),
        migrations.AlterUniqueTogether(
            name='glpivdownload',
            unique_together=set([('gLCode', 'financialYear')]),
        ),
        migrations.AlterUniqueTogether(
            name='corporatestrategy',
            unique_together=set([('corporateStrategyNo', 'financialYear')]),
        ),
    ]
