# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatestrategy',
            name='financialYear',
            field=models.CharField(choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='erservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='generalservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='financialYear',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='ibmdata',
            name='financialYear',
            field=models.CharField(choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ncservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ncstrategicplan',
            name='financialYear',
            field=models.CharField(choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='financialYear',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='pvsservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sfmservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
    ]
