# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0002_auto_20170904_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erservicepriority',
            name='categoryID',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='erservicepriority',
            name='servicePriorityNo',
            field=models.CharField(db_index=True, default='-1', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalservicepriority',
            name='categoryID',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalservicepriority',
            name='servicePriorityNo',
            field=models.CharField(db_index=True, default='-1', max_length=100),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='account',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='activity',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='costCentre',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='division',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='regionBranch',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='resource',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='service',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ibmdata',
            name='budgetArea',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ibmdata',
            name='corporatePlanNo',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ibmdata',
            name='costCentre',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='ibmdata',
            name='projectSponsor',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ibmdata',
            name='service',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ibmdata',
            name='strategicPlanNo',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ncservicepriority',
            name='categoryID',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ncservicepriority',
            name='servicePriorityNo',
            field=models.CharField(db_index=True, default='-1', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvsservicepriority',
            name='categoryID',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pvsservicepriority',
            name='servicePriorityNo',
            field=models.CharField(db_index=True, default='-1', max_length=100),
        ),
        migrations.AlterField(
            model_name='sfmservicepriority',
            name='categoryID',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sfmservicepriority',
            name='servicePriorityNo',
            field=models.CharField(db_index=True, default='-1', max_length=100),
        ),
    ]
