# Generated by Django 2.0.3 on 2018-03-26 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0003_auto_20170908_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcomes',
            options={'verbose_name_plural': 'outcomes'},
        ),
    ]
