# Generated by Django 2.1 on 2018-08-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0004_auto_20180326_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePriorityMappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financialYear', models.CharField(choices=[('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100)),
                ('costCentreNo', models.CharField(max_length=4)),
                ('wildlifeManagement', models.CharField(max_length=100)),
                ('parksManagement', models.CharField(max_length=100)),
                ('forestManagement', models.CharField(max_length=100)),
            ],
        ),
    ]
