# Generated by Django 2.1 on 2018-08-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0005_serviceprioritymappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprioritymappings',
            name='costcentreName',
            field=models.CharField(default='parks', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprioritymappings',
            name='regionSubDirectorate',
            field=models.CharField(default='parks', max_length=100),
            preserve_default=False,
        ),
    ]
