# Generated by Django 2.1 on 2018-08-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0006_auto_20180813_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprioritymappings',
            old_name='costcentreName',
            new_name='costCentreName',
        ),
    ]
