# Generated by Django 2.1 on 2018-08-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0007_auto_20180813_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprioritymappings',
            options={'verbose_name_plural': 'Service Priority Mappings'},
        ),
        migrations.RemoveField(
            model_name='serviceprioritymappings',
            name='costCentreName',
        ),
        migrations.RemoveField(
            model_name='serviceprioritymappings',
            name='regionSubDirectorate',
        ),
        migrations.AlterField(
            model_name='corporatestrategy',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='erservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='generalservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ibmdata',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ncservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ncstrategicplan',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pvsservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprioritymappings',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sfmservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20')], db_index=True, max_length=100),
        ),
    ]
