# Generated by Django 2.1.10 on 2019-07-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0008_auto_20180815_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glpivdownload',
            name='codeID',
            field=models.CharField(db_index=True, help_text="This should match an IBMData object's IBMIdentifier field.", max_length=30),
        ),
    ]
