# Generated by Django 2.1.11 on 2019-08-08 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfm', '0001_squashed_0003_auto_20180319_0924'),
        ('ibms', '0009_auto_20190708_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatestrategy',
            name='fy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.FinancialYear'),
        ),
        migrations.AddField(
            model_name='erservicepriority',
            name='fy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.FinancialYear'),
        ),
        migrations.AddField(
            model_name='generalservicepriority',
            name='fy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.FinancialYear'),
        ),
        migrations.AddField(
            model_name='glpivdownload',
            name='fy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.FinancialYear'),
        ),
        migrations.AddField(
            model_name='ibmdata',
            name='fy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.FinancialYear'),
        ),
        migrations.AddField(
            model_name='ncservicepriority',
            name='fy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.FinancialYear'),
        ),
        migrations.AddField(
            model_name='ncstrategicplan',
            name='fy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.FinancialYear'),
        ),
        migrations.AddField(
            model_name='outcomes',
            name='fy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.FinancialYear'),
        ),
        migrations.AddField(
            model_name='pvsservicepriority',
            name='fy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.FinancialYear'),
        ),
        migrations.AddField(
            model_name='serviceprioritymappings',
            name='fy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.FinancialYear'),
        ),
        migrations.AddField(
            model_name='sfmservicepriority',
            name='fy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='corporatestrategy',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20'), ('2020/21', '2020/21')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='erservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20'), ('2020/21', '2020/21')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='generalservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20'), ('2020/21', '2020/21')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ibmdata',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20'), ('2020/21', '2020/21')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ncservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20'), ('2020/21', '2020/21')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ncstrategicplan',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20'), ('2020/21', '2020/21')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pvsservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20'), ('2020/21', '2020/21')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprioritymappings',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20'), ('2020/21', '2020/21')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sfmservicepriority',
            name='financialYear',
            field=models.CharField(choices=[('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17'), ('2017/18', '2017/18'), ('2018/19', '2018/19'), ('2019/20', '2019/20'), ('2020/21', '2020/21')], db_index=True, max_length=100),
        ),
    ]
