# Generated by Django 2.1.11 on 2019-08-14 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfm', '0001_squashed_0003_auto_20180319_0924'),
        ('ibms', '0010_auto_20190808_1104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='corporatestrategy',
            unique_together={('corporateStrategyNo', 'fy')},
        ),
        migrations.AlterUniqueTogether(
            name='glpivdownload',
            unique_together={('gLCode', 'fy')},
        ),
        migrations.AlterUniqueTogether(
            name='ibmdata',
            unique_together={('ibmIdentifier', 'fy')},
        ),
        migrations.AlterUniqueTogether(
            name='ncservicepriority',
            unique_together={('servicePriorityNo', 'fy')},
        ),
        migrations.AlterUniqueTogether(
            name='ncstrategicplan',
            unique_together={('strategicPlanNo', 'fy')},
        ),
    ]
