# Generated by Django 2.1.11 on 2019-09-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0011_auto_20190814_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporatestrategy',
            name='financialYear',
        ),
        migrations.RemoveField(
            model_name='erservicepriority',
            name='financialYear',
        ),
        migrations.RemoveField(
            model_name='generalservicepriority',
            name='financialYear',
        ),
        migrations.RemoveField(
            model_name='glpivdownload',
            name='financialYear',
        ),
        migrations.RemoveField(
            model_name='ibmdata',
            name='financialYear',
        ),
        migrations.RemoveField(
            model_name='ncservicepriority',
            name='financialYear',
        ),
        migrations.RemoveField(
            model_name='ncstrategicplan',
            name='financialYear',
        ),
        migrations.RemoveField(
            model_name='outcomes',
            name='financialYear',
        ),
        migrations.RemoveField(
            model_name='pvsservicepriority',
            name='financialYear',
        ),
        migrations.RemoveField(
            model_name='serviceprioritymappings',
            name='financialYear',
        ),
        migrations.RemoveField(
            model_name='sfmservicepriority',
            name='financialYear',
        ),
    ]
