# Generated by Django 2.1.11 on 2019-09-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0012_auto_20190905_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='glpivdownload',
            name='download_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
