# Generated by Django 4.2.16 on 2024-11-18 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfm', '0009_auto_20210913_0858'),
        ('ibms', '0015_remove_ibmdata_corporateplanno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibmdata',
            name='fy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfm.financialyear', verbose_name='financial year'),
        ),
    ]
