# Generated by Django 4.2.16 on 2024-11-18 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0016_alter_ibmdata_fy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ncstrategicplan',
            old_name='Action',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='ncstrategicplan',
            old_name='ActionNo',
            new_name='actionNo',
        ),
        migrations.RenameField(
            model_name='ncstrategicplan',
            old_name='Aim1',
            new_name='aim1',
        ),
        migrations.RenameField(
            model_name='ncstrategicplan',
            old_name='Aim2',
            new_name='aim2',
        ),
        migrations.RenameField(
            model_name='ncstrategicplan',
            old_name='AimNo',
            new_name='aimNo',
        ),
    ]
