# Generated by Django 4.2.18 on 2025-05-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0017_rename_action_ncstrategicplan_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glpivdownload',
            name='fybudget',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='ptdActual',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='ptdBudget',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='ytdActual',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='ytdBudget',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='ytdVariance',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
