# Generated by Django 4.2.18 on 2025-02-07 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0017_rename_action_ncstrategicplan_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glpivdownload',
            name='ibmdata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glpivdownload', to='ibms.ibmdata'),
        ),
    ]
