# Generated by Django 4.2.20 on 2025-05-02 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0018_alter_glpivdownload_fybudget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glpivdownload',
            name='ibmdata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glpivdownload', to='ibms.ibmdata'),
        ),
    ]
