# Generated by Django 5.2.2 on 2025-06-13 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0019_glpivdownload_ibmdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ibmdata',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last modified'),
        ),
        migrations.AddField(
            model_name='ibmdata',
            name='modifier',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ibms_ibmdata_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
    ]
