# Generated by Django 5.2.7 on 2025-10-16 04:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ibms", "0021_alter_ibmdata_ibmidentifier"),
        ("sfm", "0009_auto_20210913_0858"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServicePriorityMappings",
            new_name="ServicePriorityMapping",
        ),
        migrations.AlterModelOptions(
            name="serviceprioritymapping",
            options={},
        ),
        migrations.RenameModel(
            old_name="Outcomes",
            new_name="Outcome",
        ),
        migrations.AlterModelOptions(
            name="outcome",
            options={},
        ),
    ]
