# Generated by Django 5.2.6 on 2025-09-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0021_alter_ibmdata_ibmidentifier'),
        ('sfm', '0009_auto_20210913_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicePriorityMappings',
            new_name='ServicePriorityMapping',
        ),
        migrations.AlterModelOptions(
            name='serviceprioritymapping',
            options={},
        ),
    ]
