# Generated by Django 5.2.6 on 2025-09-23 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0022_rename_serviceprioritymappings_serviceprioritymapping_and_more'),
        ('sfm', '0009_auto_20210913_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatestrategy',
            name='fy',
            field=models.ForeignKey(default='TBC', on_delete=django.db.models.deletion.PROTECT, to='sfm.financialyear', verbose_name='financial year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='erservicepriority',
            name='fy',
            field=models.ForeignKey(default='TBC', on_delete=django.db.models.deletion.PROTECT, to='sfm.financialyear', verbose_name='financial year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generalservicepriority',
            name='fy',
            field=models.ForeignKey(default='TBC', on_delete=django.db.models.deletion.PROTECT, to='sfm.financialyear', verbose_name='financial year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='account',
            field=models.IntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='actNameNo',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='activity',
            field=models.CharField(db_index=True, editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='activityName',
            field=models.CharField(editable=False, max_length=100, verbose_name='activity name'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='ccName',
            field=models.CharField(editable=False, max_length=100, verbose_name='CC name'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='codeID',
            field=models.CharField(db_index=True, editable=False, help_text="This should match an IBMData object's IBMIdentifier field.", max_length=30, verbose_name='code ID'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='costCentre',
            field=models.CharField(db_index=True, editable=False, max_length=4, verbose_name='cost centre'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='division',
            field=models.CharField(db_index=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='downloadPeriod',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='download_period',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='expenseRevenue',
            field=models.CharField(editable=False, max_length=7, verbose_name='expense revenue'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='fireActivities',
            field=models.CharField(editable=False, max_length=50, verbose_name='fire activities'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='fy',
            field=models.ForeignKey(default='TBC', editable=False, on_delete=django.db.models.deletion.PROTECT, to='sfm.financialyear', verbose_name='financial year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='fybudget',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='gLCode',
            field=models.CharField(editable=False, max_length=30, verbose_name='GL code'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='ibmdata',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glpivdownload', to='ibms.ibmdata', verbose_name='IBM data'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='job',
            field=models.CharField(editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='jobName',
            field=models.CharField(editable=False, max_length=100, verbose_name='job name'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='mPRACategory',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='projNameNo',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='project',
            field=models.CharField(editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='projectName',
            field=models.CharField(editable=False, max_length=100, verbose_name='project name'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='ptdActual',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='ptdBudget',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='regionBranch',
            field=models.CharField(db_index=True, editable=False, max_length=100, verbose_name='region branch'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='resNameNo',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='resource',
            field=models.IntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='resourceCategory',
            field=models.CharField(editable=False, max_length=100, verbose_name='resource category'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='resourceName',
            field=models.CharField(editable=False, max_length=100, verbose_name='resource name'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='service',
            field=models.IntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='serviceName',
            field=models.CharField(editable=False, max_length=100, verbose_name='service name'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='shortCode',
            field=models.CharField(editable=False, max_length=20, verbose_name='short code'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='shortCodeName',
            field=models.CharField(editable=False, max_length=200, verbose_name='short code name'),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='wildfire',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='ytdActual',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='ytdBudget',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='glpivdownload',
            name='ytdVariance',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='ncservicepriority',
            name='fy',
            field=models.ForeignKey(default='TBC', on_delete=django.db.models.deletion.PROTECT, to='sfm.financialyear', verbose_name='financial year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ncstrategicplan',
            name='fy',
            field=models.ForeignKey(default='TBC', on_delete=django.db.models.deletion.PROTECT, to='sfm.financialyear', verbose_name='financial year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='fy',
            field=models.ForeignKey(default='TBC', on_delete=django.db.models.deletion.PROTECT, to='sfm.financialyear', verbose_name='financial year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pvsservicepriority',
            name='fy',
            field=models.ForeignKey(default='TBC', on_delete=django.db.models.deletion.PROTECT, to='sfm.financialyear', verbose_name='financial year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceprioritymapping',
            name='fy',
            field=models.ForeignKey(default='TBC', on_delete=django.db.models.deletion.PROTECT, to='sfm.financialyear', verbose_name='financial year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sfmservicepriority',
            name='fy',
            field=models.ForeignKey(default='TBC', on_delete=django.db.models.deletion.PROTECT, to='sfm.financialyear', verbose_name='financial year'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DepartmentProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_program1', models.CharField(blank=True, max_length=500, null=True, verbose_name='department program 1')),
                ('dept_program2', models.CharField(blank=True, max_length=500, null=True, verbose_name='department program 2')),
                ('dept_program3', models.CharField(blank=True, max_length=500, null=True, verbose_name='department program 3')),
                ('fy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfm.financialyear', verbose_name='financial year')),
                ('ibmdata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departmentprogram', to='ibms.ibmdata')),
            ],
        ),
    ]
