# Generated by Django 5.2.7 on 2025-10-22 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ibms', '0023_erservicepriority_corporate_strategy_and_more'),
        ('sfm', '0009_auto_20210913_0858'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ibmdata',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ibmdata',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='ibmdata',
            index=models.Index(fields=['content_type', 'object_id'], name='ibms_ibmdat_content_921f19_idx'),
        ),
    ]
