# Generated by Django 5.2.6 on 2025-09-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0023_alter_corporatestrategy_fy_and_more'),
        ('sfm', '0009_auto_20210913_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outcomes',
            new_name='Outcome',
        ),
        migrations.AlterModelOptions(
            name='outcome',
            options={},
        ),
    ]
