# Generated by Django 5.2.6 on 2025-09-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0024_rename_outcomes_outcome_alter_outcome_options'),
        ('sfm', '0009_auto_20210913_0858'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentprogram',
            unique_together={('fy', 'ibmdata')},
        ),
    ]
