# Generated by Django 5.2.8 on 2025-11-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0024_ibmdata_content_type_ibmdata_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibmdata',
            name='ibmIdentifier',
            field=models.CharField(db_index=True, max_length=100, verbose_name='IBM identifier'),
        ),
    ]
