# Generated by Django 5.2.9 on 2025-12-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibms', '0025_alter_ibmdata_ibmidentifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erservicepriority',
            name='ibmdata',
        ),
        migrations.RemoveField(
            model_name='generalservicepriority',
            name='ibmdata',
        ),
        migrations.RemoveField(
            model_name='ncservicepriority',
            name='ibmdata',
        ),
        migrations.RemoveField(
            model_name='pvsservicepriority',
            name='ibmdata',
        ),
        migrations.RemoveField(
            model_name='sfmservicepriority',
            name='ibmdata',
        ),
    ]
