apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibms
spec:
  template:
    spec:
      containers:
      - name: ibms
        #image: ghcr.io/dbca-wa/ibms:latest
        imagePullPolicy: Always
        env:
        - name: IBMS_URL
          value: "https://ibms-uat.dbca.wa.gov.au"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ibms-env-uat
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ibms-env-uat
              key: SECRET_KEY
