apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ibms
  labels:
    app: ibms-uat
spec:
  ingressClassName: nginx
  rules:
  - host: ibms-uat.dbca.wa.gov.au
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ibms-clusterip-uat
            port:
              number: 8080
