apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -uat
secretGenerator:
  - name: ibms-env
    type: Opaque
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base
  - ingress.yml
  - pdb.yml
labels:
  - includeSelectors: true
    pairs:
      variant: uat
patches:
  - path: webserver_patch.yml
  - path: webserver_hpa_patch.yml
  - path: service_patch.yml
  - path: task_worker_patch.yml
