apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
secretGenerator:
  - name: ibms-env
    type: Opaque
    envs:
    - .env
resources:
  - ../../base
  - ingress.yaml
  - pdb.yaml
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: ghcr.io/dbca-wa/ibms
    newTag: 2.8.2
patches:
  - path: deployment_patch.yaml
  - path: service_patch.yaml
