apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
secretGenerator:
- envs:
  - .env
  name: ibms-env
resources:
- ../../base
- service.yaml
- ingress.yaml
- pdb.yaml
labels:
- includeSelectors: true
  pairs:
    variant: prod
patches:
- path: deployment_prod_patch.yaml
