bases:
- ../../base
namespace: ibms
nameSuffix: -prod
secretGenerator:
- name: ibms-env
  envs:
  - .env
commonLabels:
  variant: prod
resources:
- service.yaml
- ingress.yaml
patchesStrategicMerge:
- deployment_prod_patch.yaml
- statefulset_prod_patch.yaml
