apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
secretGenerator:
  - name: ibms-env
    type: Opaque
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base
  - ingress.yml
  - pdb.yml
labels:
  - includeSelectors: true
    pairs:
      variant: prod
patches:
  - path: webserver_patch.yml
  - path: webserver_hpa_patch.yml
  - path: service_patch.yml
  - path: task_worker_patch.yml
images:
  - name: ghcr.io/dbca-wa/ibms
    newTag: 2.12.3
