# Generated by Django 2.1.11 on 2019-08-14 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfm', '0001_squashed_0003_auto_20180319_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarter',
            old_name='financialYear',
            new_name='fy',
        ),
        migrations.RenameField(
            model_name='sfmmetric',
            old_name='financialYear',
            new_name='fy',
        ),
        migrations.AlterUniqueTogether(
            name='sfmmetric',
            unique_together={('fy', 'metricID')},
        ),
    ]
