# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfm', '0002_auto_20150811_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementvalue',
            name='costCentre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfm.CostCentre', verbose_name='Related Cost Centre'),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='measurementType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.MeasurementType', verbose_name='Related MeasurementType'),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfm.Quarter', verbose_name='Related Quarter'),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='sfmMetric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfm.SFMMetric', verbose_name='Related SFMMetric'),
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='costCentre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfm.CostCentre'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='financialYear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfm.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='sfmmetric',
            name='financialYear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfm.FinancialYear'),
        ),
    ]
