# Generated by Django 3.1.6 on 2021-03-29 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfm', '0002_auto_20190814_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sfmmetric',
            options={'verbose_name': 'SFM metric'},
        ),
        migrations.AddField(
            model_name='measurementvalue',
            name='planned',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='measurementvalue',
            name='status',
            field=models.CharField(blank=True, choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='costCentre',
            field=models.CharField(max_length=6, verbose_name='cost centre'),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='financialYear',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='financial year'),
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='costCentre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfm.costcentre', verbose_name='cost centre'),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='measurementType',
            field=models.ForeignKey(blank=True, help_text='Deprecated field', null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.measurementtype'),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfm.quarter'),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='sfmMetric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfm.sfmmetric', verbose_name='SFM metric'),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='value',
            field=models.FloatField(blank=True, help_text='Deprecated field', null=True),
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='costCentre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfm.costcentre', verbose_name='cost centre'),
        ),
        migrations.AlterField(
            model_name='sfmmetric',
            name='descriptor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sfmmetric',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sfmmetric',
            name='metricID',
            field=models.TextField(blank=True, null=True, verbose_name='metric ID'),
        ),
        migrations.AlterField(
            model_name='sfmmetric',
            name='servicePriorityNo',
            field=models.CharField(blank=True, default='-1', max_length=100, verbose_name='service priority number'),
        ),
    ]
