# Generated by Django 3.1.6 on 2021-04-23 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfm', '0003_auto_20210329_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementvalue',
            name='measurementType',
            field=models.ForeignKey(blank=True, help_text='Deprecated field', null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.measurementtype', verbose_name='measurement type'),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='planned',
            field=models.BooleanField(null=True, verbose_name='action planned'),
        ),
    ]
