# Generated by Django 3.1.6 on 2021-04-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfm', '0004_auto_20210423_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementvalue',
            name='status',
            field=models.CharField(blank=True, choices=[('not started', 'Not started'), ('in progress', 'In progress'), ('completed', 'Completed')], max_length=64, null=True),
        ),
    ]
