# Generated by Django 3.2.4 on 2021-08-30 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfm', '0007_costcentre_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costcentre',
            options={'ordering': ('costCentre',)},
        ),
        migrations.AlterModelOptions(
            name='financialyear',
            options={'ordering': ('financialYear',)},
        ),
        migrations.AlterModelOptions(
            name='quarter',
            options={'ordering': ('fy', 'quarter')},
        ),
        migrations.AlterModelOptions(
            name='sfmmetric',
            options={'ordering': ('fy', 'region', 'metricID'), 'verbose_name': 'SFM metric'},
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='costCentre',
            field=models.CharField(max_length=6, unique=True, verbose_name='cost centre'),
        ),
        migrations.AlterField(
            model_name='sfmmetric',
            name='fy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sfm.financialyear', verbose_name='financial year'),
        ),
        migrations.AlterField(
            model_name='sfmmetric',
            name='metricID',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='metric ID'),
        ),
    ]
