# Generated by Django 3.2.4 on 2021-09-13 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfm', '0008_auto_20210830_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementvalue',
            name='region',
            field=models.CharField(blank=True, choices=[('Goldfields', 'Goldfields'), ('Kimberley', 'Kimberley'), ('Midwest', 'Midwest'), ('Pilbara', 'Pilbara'), ('South Coast', 'South Coast'), ('South West', 'South West'), ('Swan', 'Swan'), ('Warren', 'Warren'), ('Wheatbelt', 'Wheatbelt')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='measurementvalue',
            name='costCentre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sfm.costcentre', verbose_name='cost centre'),
        ),
    ]
