apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ibms-deployment-hpa
spec:
  # Set a min of 2 replicas in order to allow our PDB.
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
  metrics:
    - resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 500
      type: Resource
