# Generated by Django 5.2.17 on 2026-10-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ibms", "0029_rename_financialyear_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glpivdownload",
            name="download_period",
            field=models.DateField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
